### PR TITLE
Error handling and redirects

### PR DESCRIPTION
**Pull request by frandiox**
@subhendukundu @huygn Hello! If you have some time, would you give me some feedback about this error handling feature?

Basically, this enables throwing errors in API or Props handlers and have Vitedge return a well-formed JSON payload.

Something like this:

```js
// props or api handler
export default ({
  handler(...) {
     if (condition) {
       throw new BadRequestError('My error message', { code: 'malformed' })
     }

     return { data: {} }
  }
})
```

The payload returned would be:

```js
{
  error: {
    status: 400,
    message: 'My error message',
    details: { code: 'malformed' }
  }
}
```

This error format can be modified in user-land, but I haven't decided yet exactly how (for now there is a `setErrorTransformer` function to do this, but needs to be refined). New errors can also be created by just extending `RestError` class.

--

With this basically a page component will get an `error` prop that contains status, message and details, so it can render anything or redirect to another route.

Thoughts? Do you think it's useful like this?
Thanks!

### CODE REVIEW

**Comment by subhendukundu** [comment]
Every framework is unique their own way. So I am gonna stop relating them to others. Having said that, I think this is great to start with. We have all the basics in place.
I would be keen to have more examples in the docs. Tho this can be a different PR. Probably we can think about a Docs strategy?

**Comment by frandiox** [comment]
@subhendukundu Thanks! Yeah that would be a different feature, I think returning something like "redirect" should work, and that will just skip the rendering.

I'm tempted to move `status` and `statusText` outside of `options`, at the top level of the returned object 🤔

**Comment by subhendukundu** [comment]
How about a conditional status code then? 
I mean if had to send a status code based on another fetch call, I wouldn't able to do that if you move it top-level right?

**Comment by frandiox** [comment]
@subhendukundu I meant this:

```js
return {
  status: 200,
  data: {}
}
```

instead of:

```js
return {
  data: {}
  options: { status: 200 }
}
```

**Comment by subhendukundu** [comment]
```
return {
  status: 200,
  data: {}
}
```
Yup, I would like this more, of course!

**Comment by huygn** [comment]
For me I would totally love the error throwing approach with extra details 👍 much over returning an `{ error: }` kind of object since its easy to skip while throwing err is much more "semantic"

**Comment by frandiox** [comment]
@huygn Thanks! Alright, I think I'll finish this up and merge it then.

@subhendukundu I've got a basic redirect working by just returning ` { status: 3xx, headers: { location: '/...' } }` from the props handler 🎉 
I guess I can add some syntax sugar on top of it so the user doesn't need to deal with http codes and headers manually.

**Comment by subhendukundu** [comment]
Phew! I am fan, sir! Officially 🙂

**Comment by frandiox** [comment]
@subhendukundu The redirect is implemented 🎉  . I had to use a mock http code to bypass some fetch issues 😅 

What's left:
- Syntax sugar `{ redirect: { permanent: true, location: '...' } }`. (Using `location` instead of `destination` to match the Location header in HTTP).
- Docs

**Comment by subhendukundu** [comment]
I am ready to test this as soon you ship this. 😋

**Comment by frandiox** [comment]
@subhendukundu Thanks, that would be great! We have a VitePress docs site in the repo. I guess we can add a new page for "errors", and maybe a "redirects" section in the "props" page? 🤔

**Comment by frandiox** [comment]
I'm going to release this without the syntax sugar for now. I think `{ status: 302, headers: { location: '/post/2' } }` is quite simple to understand as long as it's explained in the docs 🤔

**Comment by subhendukundu** [comment]
Umm sure that at least lets us test it.
Let's add a backlog or a roadmap kinda board? Where we can track them?

**Comment by frandiox** [comment]
@subhendukundu Released in `0.11.0`. 
For minor things perhaps just as issues is enough. If it's something very important then I like adding it to the readme for visibility 🤔

**Pull request merged**
